Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/LineLength:
  Max: 160
  Exclude:
    - 'test/low_level_test.rb'

Metrics/MethodLength:
  Max: 24
  Exclude:
    - 'test/low_level_test.rb'

Layout/ParameterAlignment:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: false

# Configuration parameters: Exclude.
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

# Offense count: 16
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Layout/FirstParameterIndentation:
  Exclude:
    - 'lib/argon2.rb'
    - 'test/low_level_test.rb'
    - 'test/util_test.rb'

Style/HashSyntax:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Layout/FirstArrayElementIndentation:
  Exclude:
    - 'lib/argon2/errors.rb'

# Offense count: 44
# Cop supports --auto-correct.
Layout/LeadingCommentSpace:
  Exclude:
    - 'ext/argon2_wrap/extconf.rb'

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/WordArray:
  MinSize: 33

Layout/MultilineMethodCallBraceLayout:
  Exclude:
    - 'lib/argon2.rb'
    - 'test/low_level_test.rb'

Gemspec/RequiredRubyVersion:
  Enabled: false
